# Generated by Django 4.2.4 on 2023-08-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("a+", "A+"),
                    ("a-", "A-"),
                    ("b+", "B+"),
                    ("b-", "B-"),
                    ("ab+", "AB+"),
                    ("ab-", "AB-"),
                    ("o+", "O+"),
                    ("o-", "O-"),
                ],
                default="a+",
                max_length=10,
            ),
        ),
    ]
