# Generated by Django 4.2.4 on 2023-08-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_blood_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a+", "A+"),
                    ("a-", "A-"),
                    ("b+", "B+"),
                    ("b-", "B-"),
                    ("ab+", "AB+"),
                    ("ab-", "AB-"),
                    ("o+", "O+"),
                    ("o-", "O-"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
