# Generated by Django 4.2.4 on 2023-08-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blood_request", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("a+", "A+"),
                    ("a-", "A-"),
                    ("b+", "B+"),
                    ("b-", "B-"),
                    ("ab+", "AB+"),
                    ("ab-", "AB-"),
                    ("o+", "O+"),
                    ("o-", "O-"),
                ],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="BloodGroup",
        ),
    ]
