# Generated by Django 4.2.4 on 2023-08-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blood_request", "0002_alter_bloodrequest_blood_group_delete_bloodgroup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodrequest",
            name="blood_group",
        ),
    ]
